---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Authors
- type: directory
  path: content/author
  label: Authors
  create: documents
  match: "*.md"
- type: heading
  label: Blog Posts
- type: directory
  path: content/post
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Pages
- type: document
  path: content/about/_index.md
  label: About
- type: document
  path: content/contact/_index.md
  label: Contact
- type: document
  path: content/privacy-policy/_index.md
  label: Privacy Policy
- type: heading
  label: Configuration
- type: document
  path: config.yaml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.79.0
